execution_order:
  - organization
  - location
  - patient
  - encounter
  - encounter_ed
  - encounter_icu
  - medication
  - medication_mix
  - medication_request
  - specimen
  - condition
  - condition_ed
  - procedure
  - procedure_ed
  - procedure_icu
  - observation_labevents
  - observation_micro_test
  - observation_micro_org
  - observation_micro_susc
  - observation_chartevents
  - observation_datetimeevents
  - observation_outputevents
